pygame 2.0.1 (SDL 2.0.14, Python 3.7.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "general_launch.py", line 59, in <module>
    launch_rollout(parser_args.env, parser_args.method, parser_args.save_id)
  File "general_launch.py", line 16, in launch_rollout
    args = get_general_args(env, method)
  File "/home/zihan/research/MARS/mars/utils/func.py", line 101, in get_general_args
    args = LoadYAML2Dict(path+yaml_file, toAttr=True, mergeWith='mars/confs/default.yaml')
  File "/home/zihan/research/MARS/mars/utils/func.py", line 36, in LoadYAML2Dict
    with open(yaml_file + '.yaml') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mars/confs/pettingzoo/surround_v1/pettingzoo_surround_v1_fictitiousselfplay2.yaml'
